apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kag2qh0i3-go
  janus-idp.io/tekton: kag2qh0i3-go
  backstage.io/kubernetes-id: kag2qh0i3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kag2qh0i3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
