apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kag2qh0i3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kag2qh0i3-go 
  name: kag2qh0i3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kag2qh0i3-go 
